# Generated by Django 4.0.1 on 2022-01-15 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_keygen_datetime_keygen_id_alter_keygen_id_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keygen',
            old_name='id_key',
            new_name='dateTime',
        ),
        migrations.RemoveField(
            model_name='keygen',
            name='id',
        ),
        migrations.AddField(
            model_name='keygen',
            name='idKey',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
